/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AppSigninPayloadDTO {
  email: string;
  password: string;
}

export interface AppSignupPayloadDTO {
  contactNumber?: string | '' | null;
  email: string;
  firstName: string;
  lastName?: string | '' | null;
  password: string;
  phoneNumber?: string | '' | null;
}
